version: '3'

networks:
  integration-tests-example-test:
    driver: bridge

services:
  listd_tests:
    build:
      context: .
      dockerfile: Dockerfile.resource-unittest
    depends_on:
      - mysql
    networks:
      - integration-tests-example-test
    links:
      - mysql
  mysql:
    image: mysql:5.7.24
    ports:
      - "23306:3306"
    expose:
      - "23306"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
    ]
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-engineering
    restart: on-failure
    networks:
      - integration-tests-example-test
