// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package helloworld

import (
	eerrors "github.com/gotomicro/ego/core/eerrors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = eerrors.SupportPackageIsVersion1

var resourceErrUnknown *eerrors.EgoError
var resourceErrNotFound *eerrors.EgoError
var resourceErrListMysql *eerrors.EgoError
var resourceErrInfoMysql *eerrors.EgoError

func init() {
	resourceErrUnknown = eerrors.New(int(codes.Unknown), "engineering.helloworld.RESOURCE_ERR_UNKNOWN", Error_RESOURCE_ERR_UNKNOWN.String())
	eerrors.Register(resourceErrUnknown)
	resourceErrNotFound = eerrors.New(int(codes.NotFound), "engineering.helloworld.RESOURCE_ERR_NOT_FOUND", Error_RESOURCE_ERR_NOT_FOUND.String())
	eerrors.Register(resourceErrNotFound)
	resourceErrListMysql = eerrors.New(int(codes.Internal), "engineering.helloworld.RESOURCE_ERR_LIST_MYSQL", Error_RESOURCE_ERR_LIST_MYSQL.String())
	eerrors.Register(resourceErrListMysql)
	resourceErrInfoMysql = eerrors.New(int(codes.Internal), "engineering.helloworld.RESOURCE_ERR_INFO_MYSQL", Error_RESOURCE_ERR_INFO_MYSQL.String())
	eerrors.Register(resourceErrInfoMysql)
}

func ResourceErrUnknown() eerrors.Error {
	return resourceErrUnknown
}

func ResourceErrNotFound() eerrors.Error {
	return resourceErrNotFound
}

func ResourceErrListMysql() eerrors.Error {
	return resourceErrListMysql
}

func ResourceErrInfoMysql() eerrors.Error {
	return resourceErrInfoMysql
}
