// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protoenum/v1/protoenum.proto

package protoenumv1

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BizType int32

const (
	BizType_UNKNOWN BizType = 0
	BizType_VIDEO   BizType = 1
	BizType_PPT     BizType = 2
)

// Enum value maps for BizType.
var (
	BizType_name = map[int32]string{
		0: "UNKNOWN",
		1: "VIDEO",
		2: "PPT",
	}
	BizType_value = map[string]int32{
		"UNKNOWN": 0,
		"VIDEO":   1,
		"PPT":     2,
	}
)

func (x BizType) Enum() *BizType {
	p := new(BizType)
	*p = x
	return p
}

func (x BizType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizType) Descriptor() protoreflect.EnumDescriptor {
	return file_protoenum_v1_protoenum_proto_enumTypes[0].Descriptor()
}

func (BizType) Type() protoreflect.EnumType {
	return &file_protoenum_v1_protoenum_proto_enumTypes[0]
}

func (x BizType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizType.Descriptor instead.
func (BizType) EnumDescriptor() ([]byte, []int) {
	return file_protoenum_v1_protoenum_proto_rawDescGZIP(), []int{0}
}

var File_protoenum_v1_protoenum_proto protoreflect.FileDescriptor

var file_protoenum_v1_protoenum_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x76, 0x31, 0x2a, 0x2a, 0x0a, 0x07,
	0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x50, 0x50, 0x54, 0x10, 0x02, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x6e,
	0x75, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoenum_v1_protoenum_proto_rawDescOnce sync.Once
	file_protoenum_v1_protoenum_proto_rawDescData = file_protoenum_v1_protoenum_proto_rawDesc
)

func file_protoenum_v1_protoenum_proto_rawDescGZIP() []byte {
	file_protoenum_v1_protoenum_proto_rawDescOnce.Do(func() {
		file_protoenum_v1_protoenum_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoenum_v1_protoenum_proto_rawDescData)
	})
	return file_protoenum_v1_protoenum_proto_rawDescData
}

var file_protoenum_v1_protoenum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoenum_v1_protoenum_proto_goTypes = []interface{}{
	(BizType)(0), // 0: protoenum.v1.BizType
}
var file_protoenum_v1_protoenum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoenum_v1_protoenum_proto_init() }
func file_protoenum_v1_protoenum_proto_init() {
	if File_protoenum_v1_protoenum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoenum_v1_protoenum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoenum_v1_protoenum_proto_goTypes,
		DependencyIndexes: file_protoenum_v1_protoenum_proto_depIdxs,
		EnumInfos:         file_protoenum_v1_protoenum_proto_enumTypes,
	}.Build()
	File_protoenum_v1_protoenum_proto = out.File
	file_protoenum_v1_protoenum_proto_rawDesc = nil
	file_protoenum_v1_protoenum_proto_goTypes = nil
	file_protoenum_v1_protoenum_proto_depIdxs = nil
}
